[package]
name = "twoliter"
version = "0.4.4"
edition = "2021"
description = "A command line tool for creating custom builds of Bottlerocket"
authors = ["Matthew James Briggs <brigmatt@amazon.com>"]
repository = "https://github.com/bottlerocket-os/twoliter"
license = "MIT OR Apache-2.0"
keywords = ["twoliter", "bottlerocket"]
exclude = ["/design", "/target", "/dockerfiles", "/scripts"]

[dependencies]
anyhow = "1"
async-recursion = "1"
async-walkdir = "1"
base64 = "0.22"
buildsys-config = { version = "0.1", path = "../tools/buildsys-config" }
clap = { version = "4", features = ["derive", "env", "std"] }
env_logger = "0.11"
filetime = "0.2"
flate2 = "1"
futures= "0.3"
log = "0.4"
oci-cli-wrapper = { version = "0.1", path = "../tools/oci-cli-wrapper" }
olpc-cjson = "0.1"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tar = "0.4"
tempfile = "3"
tokio = { version = "1", default-features = false, features = ["fs", "macros", "process", "rt-multi-thread"] }
toml = "0.8"
uuid = { version = "1", features = [ "v4" ] }

# Packwolf testing
packwolf = { path = "../packwolf" }
once_cell = "1.19"

# Binary dependencies. These are binaries that we want to embed in the Twoliter binary.
#buildsys = { version = "0.1.0", artifact = [ "bin:buildsys", "bin:bottlerocket-variant" ], path = "../tools/buildsys" }
#pipesys = { version = "0.1.0", artifact = [ "bin:pipesys" ], path = "../tools/pipesys" }
#pubsys = { version = "0.1.0", artifact = [ "bin:pubsys" ], path = "../tools/pubsys" }
#pubsys-setup = { version = "0.1.0", artifact = [ "bin:pubsys-setup" ], path = "../tools/pubsys-setup" }
#testsys = { version = "0.1.0", artifact = [ "bin:testsys" ], path = "../tools/testsys" }
#tuftool = { version = "0.10", artifact = [ "bin:tuftool" ] }
#unplug = { version = "0.1.0", artifact = [ "bin:unplug" ], path = "../tools/unplug" }

[build-dependencies]
bytes = "1"
flate2 = "1"
tar = "0.4"
packwolf = { path = "../packwolf" }

[features]
default = ["integ-tests"]
integ-tests = []
